<a href="https://colab.research.google.com/github/VectorJamo/Deep-Learning/blob/main/PyTorch_For_Deep_Learning_01_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensor Operations**

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
print(torch.__version__)

2.5.1+cu121


## Introduction to Tensors
### Creating Tensors

In [ ]:
# Introduction to Tensors
# Tensors are a way to represent multi-dimensional data

# Types of Tensors:
# Scalar: 0 dimensional
scalar = torch.tensor(3)
scalar

tensor(3)

In [ ]:
scalar.ndim # Prints the number of dimensions of the Tensor

0

In [ ]:
scalar.item() # Returns the item stored by the tensor object in basic datatype form (Works with only scalars)

3

In [ ]:
# Vector: 1 dimensional
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [ ]:
# You can tell the number of dimensions of a tensor in PyTorch has by the number of square brackets on the outside ([) and you only need to count one side
vector.ndim

1

In [ ]:
vector.shape # Single row of data

torch.Size([3])

In [ ]:
# Matrix: 2 dimensional
matrix = torch.tensor([[1, 2],
                       [3, 4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape # 2 Rows and 2 columns of data

torch.Size([2, 2])

In [ ]:
# n-dimensional tensor
# 3 dimesional tensor: Collection of 2 dimensional tensors(matrices)

tensor = torch.tensor([[[1, 2],
                        [3, 4]],
                        [[9, 8],
                        [7, 6]]])
tensor

tensor([[[1, 2],
         [3, 4]],

        [[9, 8],
         [7, 6]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape # 2 collections of 2x2 matrices.
# The first dimension has 2 elements(the actual numeric data).
# The second dimension has 2 elements(two rows of data).
# The third dimension has 2 elements(two rows and columns of data)

torch.Size([2, 2, 2])

  ### Tensors With Random Values


In [ ]:
tensor = torch.rand(size=(2, 2, 2)) # Create a 3d tensor. A tensor that holds 2, 2x2 matrices
tensor

tensor([[[0.9851, 0.3795],
         [0.6795, 0.5874]],

        [[0.9655, 0.7793],
         [0.6873, 0.3855]]])

In [ ]:
tensor = torch.rand(3) # Create a 1d tensor of 3 random elements
tensor

tensor([0.3740, 0.9579, 0.4658])

In [ ]:
# Create a tensor with all zeros and ones
tensor = torch.ones(4)
tensor

tensor([1., 1., 1., 1.])

In [ ]:
tensor = torch.zeros(4)
tensor

tensor([0., 0., 0., 0.])

In [ ]:
tensor = torch.zeros(size=(2, 3))
tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### Range Based Tensors
#### Use `torch.arange(start, stop, step)`

In [ ]:
tensor = torch.arange(0, 10, 1)
tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
tensor = torch.arange(-10, 10, 2)
tensor

tensor([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

### Tensor Datatypes

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

### Tensor Operations

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 10 # Adds 10 to each element in the tensor

tensor([11, 12, 13])

In [ ]:
tensor = torch.rand(size=(2, 2, 2))
tensor + 10 # Adds 10 to each element in the tensor (Same for higher dimensional tensors)

tensor([[[10.5053, 10.4860],
         [10.4276, 10.7747]],

        [[10.6074, 10.1224],
         [10.7934, 10.4855]]])

In [ ]:
tensor * 10 # Multiplies each element of the tensor with 10

tensor([[[5.0533, 4.8600],
         [4.2760, 7.7471]],

        [[6.0736, 1.2237],
         [7.9345, 4.8552]]])

In [ ]:
tensor - 10 # Subtracts each element of the tensor by 10

tensor([[[-9.4947, -9.5140],
         [-9.5724, -9.2253]],

        [[-9.3926, -9.8776],
         [-9.2066, -9.5145]]])

#### Matrix Multiplication
##### One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.
##### PyTorch implements matrix multiplication functionality in the `torch.matmul()` or `torch.mm()` method.


In [ ]:
tensor1 = torch.tensor([1, 2, 3]) # 1x2 matrix
tensor2 = torch.tensor([4, 5, 6]) # 1x2 matrix

tensor3 = tensor1.matmul(tensor2) # [1*4 + 2*5 + 3*6]. Regular matrix multiplication.
tensor3

tensor(32)

All the same rules of matrix multiplications apply

In [ ]:
tensor1 = torch.rand(size=(2, 2))
tensor2 = torch.rand(size=(2, 2))
tensor3 = tensor1.matmul(tensor2)
tensor3

tensor([[0.2798, 0.4937],
        [0.1391, 0.3746]])

In [ ]:
tensor1 = torch.rand(size=(1, 2, 2))
tensor2 = torch.rand(size=(2, 2, 2))
tensor3 = tensor1.matmul(tensor2)
tensor3

tensor([[[0.2804, 0.6354],
         [0.4516, 1.0212]],

        [[0.3530, 0.5409],
         [0.5710, 0.8702]]])

Transposing matrices to make matrix multiplication work

In [ ]:
tensor1 = torch.tensor([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12]])
tensor2 = torch.tensor([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12]])


In [ ]:
tensor2 = torch.transpose(tensor2, 0, 1)

In [ ]:
torch.mm(tensor1, tensor2)

tensor([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]])

Neural networks are full of matrix multiplications and dot products.

The `torch.nn.Linear()` module, also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input x and a weights matrix W.

X = Total inputs to a NN layer. It is a matrix of **no. of neurons on the current layer times the number of neurons on the previous layer**
Hence, each row of matrix X will be fed into a neuron on that layer.

W = Weights of that layer. It has the same dimension as X. Each row of the weights matrix will be the weight of a particular neuron in that layer.

In [ ]:
# Five input samples of containing 2 elements each (5x2 matrix)
input_x = torch.tensor([1, 2], dtype=torch.float32)

# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)

# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = size of each input sample (2)
                         out_features=6) # out_features = size of the output sample for an input sample of size 2 (6)
# This is exactly what happens in a layer of a Feed Forward Neural Network

# The in_features and out_features, apart from defining our layer, also defines the shape of the weight matrix.
# Here, input matrix -> 1x2, weight matrix -> 6x2. Operation -> input*weight(transposed) + bias(bias = 0 in this case)
output = linear(input_x)
print(f"Input shape: {input_x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([2])

Output:
tensor([2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
       grad_fn=<ViewBackward0>)

Output shape: torch.Size([6])


### Finding the min, max, mean, sum, etc (aggregation)

In [ ]:
x = torch.arange(1, 10, 1)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 1
Maximum: 9
Mean: 5.0
Sum: 45


In [ ]:
# Returns index of max and min values
print(f"Index where max value occurs: {x.argmax()}")
print(f"Index where min value occurs: {x.argmin()}")

Index where max value occurs: 8
Index where min value occurs: 0


### Change Tensor datatype

In [ ]:
# Create a tensor and check its datatype
x = torch.arange(10.0, 100.0, 10.0)
x

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [ ]:
x.dtype

torch.float32

In [ ]:
# Create a float16 tensor
x_int32 = x.type(torch.int32)
x_int32

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int32)

In [ ]:
x_int32.dtype

torch.int32

### Reshaping and stacking

In [ ]:
x = torch.tensor([1, 2, 3, 4, 5])
x, x.shape

(tensor([1, 2, 3, 4, 5]), torch.Size([5]))

In [ ]:
x = x.reshape(1, 5) # Add an extra dimension with reshape(new size)
x

tensor([[1, 2, 3, 4, 5]])

In [ ]:
x.shape

torch.Size([1, 5])

In [ ]:
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[[1, 2, 3, 4, 5]],

        [[1, 2, 3, 4, 5]],

        [[1, 2, 3, 4, 5]],

        [[1, 2, 3, 4, 5]]])

In [ ]:
x1 = torch.tensor([1, 2, 3, 4])
x2 = torch.tensor([5, 6, 7, 8])
x3 = torch.stack([x1, x2])
x3

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

### Indexing: Selecting data from Tensors
#### If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Indexing values goes outer dimension -> inner dimension (check out the square brackets).
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [ ]:
# Get ALL values of 0th dimension (most outer dimension) and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])