<a href="https://colab.research.google.com/github/VectorJamo/Deep-Learning/blob/main/Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Tensors
import torch
import numpy as np

In [28]:
# @title Numpy arrays

numpy_array = np.array([1, 2, 3])
print(numpy_array)

numpy_random_2d = np.random.rand(3, 3)
print(numpy_random_2d)

[1 2 3]
[[0.69333478 0.4054503  0.75598161]
 [0.55058715 0.2353924  0.68221985]
 [0.17069925 0.77038619 0.79824931]]


In [25]:

tensor_array_2d = torch.rand(3, 3)
print(tensor_array_2d)

# Think of a 3 dimesional tensor as an array of 3 matrices each with dimensions of 2x4
tensor_array_3d = torch.rand(3, 2, 4)
print(tensor_array_3d)



tensor([[0.9158, 0.8096, 0.0477],
        [0.8401, 0.5628, 0.3430],
        [0.5223, 0.9997, 0.9029]])
tensor([[[0.0843, 0.9566, 0.7307, 0.9435],
         [0.1656, 0.9560, 0.6398, 0.9834]],

        [[0.9991, 0.7177, 0.5583, 0.4188],
         [0.1772, 0.0906, 0.8905, 0.5456]],

        [[0.8438, 0.3976, 0.1905, 0.8793],
         [0.2822, 0.4136, 0.9695, 0.7005]]])


In [11]:
# Create tensor out of numpy array
tensor_from_numpy = torch.from_numpy(numpy_array)
print(tensor_from_numpy)

tensor([1, 2, 3])


In [22]:
my_tensor = torch.arange(10)
print(my_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [24]:
# Reshape tensors
my_tensor = my_tensor.reshape(2, 5)
print(my_tensor)

# Reshape if we dont know the number of items in the tensor
# Here, 5 says make 5 rows and -1 says populate the new tensor in such a way that you get 5 even rows of data.
my_tensor = my_tensor.reshape(5, -1)
print(my_tensor)

my_tensor = torch.arange(10)
my_tensor = my_tensor.reshape(-1, 5)
print(my_tensor)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [36]:
# Tensor math operations
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

In [37]:
# Element wise addition
print(tensor1 + tensor2)

tensor([5, 7, 9])


In [38]:
# Element wise subtraction
print(tensor1 - tensor2)

tensor([-3, -3, -3])


In [40]:
# Same for tensor wise multiplication and division
print(tensor1 * tensor2)
print(tensor1 / tensor2)

tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


In [41]:
# Modular operation
print(tensor1 % tensor2)

tensor([1, 2, 3])


In [42]:
# Exponents
print(tensor1 ** tensor2)

tensor([  1,  32, 729])


In [44]:
# Tensor assignment
tensor1  = tensor1 + tensor2
print(tensor1)

tensor([ 9, 12, 15])
