<a href="https://colab.research.google.com/github/VectorJamo/Deep-Learning/blob/main/Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Tensors
import torch
import numpy as np

In [12]:
# @title Numpy arrays

numpy_array = np.array([1, 2, 3])
print(numpy_array)

numpy_random_2d = np.random.rand(3, 3)
print(numpy_random_2d)

[1 2 3]
[[0.97178925 0.2835551  0.96204448]
 [0.02512448 0.38652883 0.44453141]
 [0.28428978 0.25184487 0.33383861]]


In [10]:
# @title Tensors

tensor_array_2d = torch.rand(3, 3)
print(tensor_array_2d)

# Think of a 3 dimesional tensor as an array of 3 matrices each with dimensions of 2x4
tensor_array_3d = torch.rand(3, 2, 4)
print(tensor_array_3d)



tensor([[0.2371, 0.5589, 0.4045],
        [0.5459, 0.2910, 0.6170],
        [0.6208, 0.1311, 0.2534]])
tensor([[[0.0133, 0.2281, 0.6500, 0.2903],
         [0.3579, 0.8495, 0.2414, 0.0706]],

        [[0.3750, 0.8283, 0.6298, 0.4614],
         [0.2597, 0.1592, 0.8475, 0.0039]],

        [[0.8451, 0.2804, 0.7788, 0.4519],
         [0.6203, 0.4174, 0.1449, 0.6443]]])


In [11]:
# Create tensor out of numpy array
tensor_from_numpy = torch.from_numpy(numpy_array)
print(tensor_from_numpy)

tensor([1, 2, 3])


In [17]:
my_tensor = torch.arange(10)
print(my_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [19]:
# Reshape tensors
my_tensor = my_tensor.reshape(2, 5)
print(my_tensor)

# Reshape if we dont know the number of items in the tensor
# Here, 5 says make 5 rows and -1 says populate the new tensor in such a way that you get 5 even rows of data.
my_tensor = my_tensor.reshape(5, -1)
print(my_tensor)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
